from lxml.etree import ElementNamespaceClassLookup, XMLParser, _Element
from pptx.oxml.xmlchemy import BaseOxmlElement

element_class_lookup: ElementNamespaceClassLookup = ...
oxml_parser: XMLParser = ...

def parse_from_template(template_file_name: str) -> _Element: ...
def parse_xml(xml: str | bytes) -> _Element: ...
def register_element_cls(nsptagname: str, cls: type[BaseOxmlElement]) -> None: ...
