from re import Pattern
from typing import Self

class PackURI(str):
    _filename_re: Pattern[str] = ...
    def __new__(cls, pack_uri_str: str) -> Self: ...
    @staticmethod
    def from_rel_ref(baseURI: str, relative_ref: str) -> PackURI: ...
    @property
    def baseURI(self) -> str: ...
    @property
    def ext(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def idx(self) -> int | None: ...
    @property
    def membername(self) -> str: ...
    def relative_ref(self, baseURI: str) -> str: ...
    @property
    def rels_uri(self) -> PackURI: ...

PACKAGE_URI: PackURI = ...
CONTENT_TYPES_URI: PackURI = ...
