from typing import Any

class CaseInsensitiveDict(dict):
    def __contains__(self, key: Any) -> bool: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
