from pptx.enum.chart import XL_LEGEND_POSITION
from pptx.text.text import Font
from pptx.util import lazyproperty

class Legend:
    def __init__(self, legend_elm) -> None: ...
    @lazyproperty
    def font(self) -> Font: ...
    @property
    def horz_offset(self) -> float | None: ...
    @horz_offset.setter
    def horz_offset(self, value: float | None) -> None: ...
    @property
    def include_in_layout(self) -> bool: ...
    @include_in_layout.setter
    def include_in_layout(self, value: bool | None) -> None: ...
    @property
    def position(self) -> XL_LEGEND_POSITION: ...
    @position.setter
    def position(self, position: XL_LEGEND_POSITION) -> None: ...
