from pptx.dml.chtfmt import ChartFormat
from pptx.enum.chart import XL_MARKER_STYLE
from pptx.shared import ElementProxy
from pptx.util import lazyproperty

class Marker(ElementProxy):
    @lazyproperty
    def format(self) -> ChartFormat: ...
    @property
    def size(self) -> int | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...
    @property
    def style(self) -> XL_MARKER_STYLE | None: ...
    @style.setter
    def style(self, value: XL_MARKER_STYLE | None) -> None: ...
