from pptx.enum.base import BaseEnum

class PP_ACTION_TYPE(BaseEnum):
    END_SHOW = ...
    FIRST_SLIDE = ...
    HYPERLINK = ...
    LAST_SLIDE = ...
    LAST_SLIDE_VIEWED = ...
    NAMED_SLIDE = ...
    NAMED_SLIDE_SHOW = ...
    NEXT_SLIDE = ...
    NONE = ...
    OPEN_FILE = ...
    OLE_VERB = ...
    PLAY = ...
    PREVIOUS_SLIDE = ...
    RUN_MACRO = ...
    RUN_PROGRAM = ...

PP_ACTION = PP_ACTION_TYPE
