from pptx.enum.base import BaseEnum, BaseXmlEnum

class XL_AXIS_CROSSES(BaseXmlEnum):
    AUTOMATIC = ...
    CUSTOM = ...
    MAXIMUM = ...
    MINIMUM = ...

class XL_CATEGORY_TYPE(BaseEnum):
    AUTOMATIC_SCALE = ...
    CATEGORY_SCALE = ...
    TIME_SCALE = ...

class XL_CHART_TYPE(BaseEnum):
    THREE_D_AREA = ...
    THREE_D_AREA_STACKED = ...
    THREE_D_AREA_STACKED_100 = ...
    THREE_D_BAR_CLUSTERED = ...
    THREE_D_BAR_STACKED = ...
    THREE_D_BAR_STACKED_100 = ...
    THREE_D_COLUMN = ...
    THREE_D_COLUMN_CLUSTERED = ...
    THREE_D_COLUMN_STACKED = ...
    THREE_D_COLUMN_STACKED_100 = ...
    THREE_D_LINE = ...
    THREE_D_PIE = ...
    THREE_D_PIE_EXPLODED = ...
    AREA = ...
    AREA_STACKED = ...
    AREA_STACKED_100 = ...
    BAR_CLUSTERED = ...
    BAR_OF_PIE = ...
    BAR_STACKED = ...
    BAR_STACKED_100 = ...
    BUBBLE = ...
    BUBBLE_THREE_D_EFFECT = ...
    COLUMN_CLUSTERED = ...
    COLUMN_STACKED = ...
    COLUMN_STACKED_100 = ...
    CONE_BAR_CLUSTERED = ...
    CONE_BAR_STACKED = ...
    CONE_BAR_STACKED_100 = ...
    CONE_COL = ...
    CONE_COL_CLUSTERED = ...
    CONE_COL_STACKED = ...
    CONE_COL_STACKED_100 = ...
    CYLINDER_BAR_CLUSTERED = ...
    CYLINDER_BAR_STACKED = ...
    CYLINDER_BAR_STACKED_100 = ...
    CYLINDER_COL = ...
    CYLINDER_COL_CLUSTERED = ...
    CYLINDER_COL_STACKED = ...
    CYLINDER_COL_STACKED_100 = ...
    DOUGHNUT = ...
    DOUGHNUT_EXPLODED = ...
    LINE = ...
    LINE_MARKERS = ...
    LINE_MARKERS_STACKED = ...
    LINE_MARKERS_STACKED_100 = ...
    LINE_STACKED = ...
    LINE_STACKED_100 = ...
    PIE = ...
    PIE_EXPLODED = ...
    PIE_OF_PIE = ...
    PYRAMID_BAR_CLUSTERED = ...
    PYRAMID_BAR_STACKED = ...
    PYRAMID_BAR_STACKED_100 = ...
    PYRAMID_COL = ...
    PYRAMID_COL_CLUSTERED = ...
    PYRAMID_COL_STACKED = ...
    PYRAMID_COL_STACKED_100 = ...
    RADAR = ...
    RADAR_FILLED = ...
    RADAR_MARKERS = ...
    STOCK_HLC = ...
    STOCK_OHLC = ...
    STOCK_VHLC = ...
    STOCK_VOHLC = ...
    SURFACE = ...
    SURFACE_TOP_VIEW = ...
    SURFACE_TOP_VIEW_WIREFRAME = ...
    SURFACE_WIREFRAME = ...
    XY_SCATTER = ...
    XY_SCATTER_LINES = ...
    XY_SCATTER_LINES_NO_MARKERS = ...
    XY_SCATTER_SMOOTH = ...
    XY_SCATTER_SMOOTH_NO_MARKERS = ...

class XL_DATA_LABEL_POSITION(BaseXmlEnum):
    ABOVE = ...
    BELOW = ...
    BEST_FIT = ...
    CENTER = ...
    INSIDE_BASE = ...
    INSIDE_END = ...
    LEFT = ...
    MIXED = ...
    OUTSIDE_END = ...
    RIGHT = ...

XL_LABEL_POSITION = XL_DATA_LABEL_POSITION

class XL_LEGEND_POSITION(BaseXmlEnum):
    BOTTOM = ...
    CORNER = ...
    CUSTOM = ...
    LEFT = ...
    RIGHT = ...
    TOP = ...

class XL_MARKER_STYLE(BaseXmlEnum):
    AUTOMATIC = ...
    CIRCLE = ...
    DASH = ...
    DIAMOND = ...
    DOT = ...
    NONE = ...
    PICTURE = ...
    PLUS = ...
    SQUARE = ...
    STAR = ...
    TRIANGLE = ...
    X = ...

class XL_TICK_MARK(BaseXmlEnum):
    CROSS = ...
    INSIDE = ...
    NONE = ...
    OUTSIDE = ...

class XL_TICK_LABEL_POSITION(BaseXmlEnum):
    HIGH = ...
    LOW = ...
    NEXT_TO_AXIS = ...
    NONE = ...
