from pptx.enum.base import BaseEnum, BaseXmlEnum

class MSO_COLOR_TYPE(BaseEnum):
    RGB = ...
    SCHEME = ...
    HSL = ...
    PRESET = ...
    SCRGB = ...
    SYSTEM = ...

class MSO_FILL_TYPE(BaseEnum):
    BACKGROUND = ...
    GRADIENT = ...
    GROUP = ...
    PATTERNED = ...
    PICTURE = ...
    SOLID = ...
    TEXTURED = ...

MSO_FILL = MSO_FILL_TYPE

class MSO_LINE_DASH_STYLE(BaseXmlEnum):
    DASH = ...
    DASH_DOT = ...
    DASH_DOT_DOT = ...
    LONG_DASH = ...
    LONG_DASH_DOT = ...
    ROUND_DOT = ...
    SOLID = ...
    SQUARE_DOT = ...
    DASH_STYLE_MIXED = ...

MSO_LINE = MSO_LINE_DASH_STYLE

class MSO_PATTERN_TYPE(BaseXmlEnum):
    CROSS = ...
    DARK_DOWNWARD_DIAGONAL = ...
    DARK_HORIZONTAL = ...
    DARK_UPWARD_DIAGONAL = ...
    DARK_VERTICAL = ...
    DASHED_DOWNWARD_DIAGONAL = ...
    DASHED_HORIZONTAL = ...
    DASHED_UPWARD_DIAGONAL = ...
    DASHED_VERTICAL = ...
    DIAGONAL_BRICK = ...
    DIAGONAL_CROSS = ...
    DIVOT = ...
    DOTTED_DIAMOND = ...
    DOTTED_GRID = ...
    DOWNWARD_DIAGONAL = ...
    HORIZONTAL = ...
    HORIZONTAL_BRICK = ...
    LARGE_CHECKER_BOARD = ...
    LARGE_CONFETTI = ...
    LARGE_GRID = ...
    LIGHT_DOWNWARD_DIAGONAL = ...
    LIGHT_HORIZONTAL = ...
    LIGHT_UPWARD_DIAGONAL = ...
    LIGHT_VERTICAL = ...
    NARROW_HORIZONTAL = ...
    NARROW_VERTICAL = ...
    OUTLINED_DIAMOND = ...
    PERCENT_10 = ...
    PERCENT_20 = ...
    PERCENT_25 = ...
    PERCENT_30 = ...
    ERCENT_40 = ...
    PERCENT_5 = ...
    PERCENT_50 = ...
    PERCENT_60 = ...
    PERCENT_70 = ...
    PERCENT_75 = ...
    PERCENT_80 = ...
    PERCENT_90 = ...
    PLAID = ...
    SHINGLE = ...
    SMALL_CHECKER_BOARD = ...
    SMALL_CONFETTI = ...
    SMALL_GRID = ...
    SOLID_DIAMOND = ...
    SPHERE = ...
    TRELLIS = ...
    UPWARD_DIAGONAL = ...
    VERTICAL = ...
    WAVE = ...
    WEAVE = ...
    WIDE_DOWNWARD_DIAGONAL = ...
    WIDE_UPWARD_DIAGONAL = ...
    ZIG_ZAG = ...
    MIXED = ...

MSO_PATTERN = MSO_PATTERN_TYPE

class MSO_THEME_COLOR_INDEX(BaseXmlEnum):
    NOT_THEME_COLOR = ...
    ACCENT_1 = ...
    ACCENT_2 = ...
    ACCENT_3 = ...
    ACCENT_4 = ...
    ACCENT_5 = ...
    ACCENT_6 = ...
    BACKGROUND_1 = ...
    BACKGROUND_2 = ...
    DARK_1 = ...
    DARK_2 = ...
    FOLLOWED_HYPERLINK = ...
    HYPERLINK = ...
    LIGHT_1 = ...
    LIGHT_2 = ...
    TEXT_1 = ...
    TEXT_2 = ...
    MIXED = ...

MSO_THEME_COLOR = MSO_THEME_COLOR_INDEX
