from pptx.enum.base import BaseEnum, BaseXmlEnum

class MSO_AUTO_SIZE(BaseEnum):
    NONE = ...
    SHAPE_TO_FIT_TEXT = ...
    TEXT_TO_FIT_SHAPE = ...
    MIXED = ...

class MSO_TEXT_UNDERLINE_TYPE(BaseXmlEnum):
    NONE = ...
    DASH_HEAVY_LINE = ...
    DASH_LINE = ...
    DASH_LONG_HEAVY_LINE = ...
    DASH_LONG_LINE = ...
    DOT_DASH_HEAVY_LINE = ...
    DOT_DASH_LINE = ...
    DOT_DOT_DASH_HEAVY_LINE = ...
    DOT_DOT_DASH_LINE = ...
    DOTTED_HEAVY_LINE = ...
    DOTTED_LINE = ...
    DOUBLE_LINE = ...
    HEAVY_LINE = ...
    SINGLE_LINE = ...
    WAVY_DOUBLE_LINE = ...
    WAVY_HEAVY_LINE = ...
    WAVY_LINE = ...
    WORDS = ...
    MIXED = ...

MSO_UNDERLINE = MSO_TEXT_UNDERLINE_TYPE

class MSO_VERTICAL_ANCHOR(BaseXmlEnum):
    TOP = ...
    MIDDLE = ...
    BOTTOM = ...
    MIXED = ...

MSO_ANCHOR = MSO_VERTICAL_ANCHOR

class PP_PARAGRAPH_ALIGNMENT(BaseXmlEnum):
    CENTER = ...
    DISTRIBUTE = ...
    JUSTIFY = ...
    JUSTIFY_LOW = ...
    LEFT = ...
    RIGHT = ...
    THAI_DISTRIBUTE = ...
    MIXED = ...

PP_ALIGN = PP_PARAGRAPH_ALIGNMENT
