from collections.abc import Callable
from typing import Any, Self

class Length(int):
    _EMUS_PER_INCH: int = ...
    _EMUS_PER_CENTIPOINT: int = ...
    _EMUS_PER_CM: int = ...
    _EMUS_PER_MM: int = ...
    _EMUS_PER_PT: int = ...
    def __new__(cls, emu: int) -> Self: ...
    @property
    def inches(self) -> float: ...
    @property
    def centipoints(self) -> int: ...
    @property
    def cm(self) -> float: ...
    @property
    def emu(self) -> int: ...
    @property
    def mm(self) -> float: ...
    @property
    def pt(self) -> float: ...

class Inches(Length):
    def __new__(cls, inches: float) -> Self: ...

class Centipoints(Length):
    def __new__(cls, centipoints: int) -> Self: ...

class Cm(Length):
    def __new__(cls, cm: float) -> Self: ...

class Emu(Length):
    def __new__(cls, emu: int) -> Self: ...

class Mm(Length):
    def __new__(cls, mm: float) -> Self: ...

class Pt(Length):
    def __new__(cls, points: float) -> Self: ...

class lazyproperty[T]:
    def __init__(self, fget: Callable[..., T]) -> None: ...
    def __get__(self, obj: Any, type: Any = ...) -> T:  # noqa: A002
        ...
    def __set__(self, obj: Any, value: Any) -> None: ...
